stages:
  - 'test'
  - 'deploy'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - 'node_modules/'

test:
  stage: 'test'
  before_script:
    - 'npm --version'
    - 'yarn --version'    
  script:
    - 'yarn install'
    - 'yarn test --coverage'
    - 'yarn lint'

deploy:
  stage: 'deploy'
  before_script:
    - 'npm config set registry https://packagecloud.io/flatsorspikes/frontend/npm/'
    - 'echo "always-auth=true" > $HOME/.npmrc'
    - 'echo "registry=https://packagecloud.io/flatsorspikes/frontend/npm/" >> $HOME/.npmrc'
    - 'echo "//packagecloud.io/flatsorspikes/frontend/npm/:_authToken=$PACKAGECLOUD_API_TOKEN" >> $HOME/.npmrc'    
  script:
    - 'yarn build'
    - 'yarn pack'
    - 'npm publish fos-shared-*.tgz'
  only:
    - 'master'
