stages:
  - 'build'
  - 'test'

before_script_defaults: &defaults
  - 'export PATH="/home/ubuntu/.nvm/versions/node/v12.18.2/bin:/home/ubuntu/.yarn/bin:/home/ubuntu/.config/yarn/global/node_modules/.bin:$PATH"'
  - 'npm --version'
  - 'yarn --version'

build:
  stage: 'build'
  before_script:
    <<: *before_script_defaults
  script:
    - 'yarn'

test:
  stage: 'test'
  before_script:
    <<: *before_script_defaults
  script:
    - 'npm test'
