stages:
  - 'build'
  - 'test'

build:
  stage: 'build'
  before_script:
    - 'echo $PATH'
    - 'npm --version'
    - 'yarn --version'
  script:
    - 'yarn'

test:
  stage: 'test'
  script:
    - 'npm test'
