stages:
  - 'build'
  - 'test'

build:
  stage: 'build'
  before_script:
    - 'export PATH="/home/ubuntu/.nvm/versions/node/v12.18.2/bin:/home/ubuntu/.yarn/bin:/home/ubuntu/.config/yarn/global/node_modules/.bin:$PATH"'
    - 'npm --version'
    - 'yarn --version'
  script:
    - 'yarn'

test:
  stage: 'test'
  before_script:
    - 'export PATH="/home/ubuntu/.nvm/versions/node/v12.18.2/bin:/home/ubuntu/.yarn/bin:/home/ubuntu/.config/yarn/global/node_modules/.bin:$PATH"'
    - 'npm --version'
    - 'yarn --version'
  script:
    - 'npm test'
